# Uncomment this line to define a global platform for your project
# platform :ios, '13.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks! :linkage => :static
   # 只在真机集成
  unless ENV['SIMULATOR_DEVICE_NAME']
    pod 'AliyunIOSNuiSDK', :git => '/Users/andy/zwork/code/AliyunIOSNuiSDK'
  end
  pod 'AliVCSDK_ARTC', '7.3.0'

  # AI实时互动通话场景SDK
  pod 'ARTCAICallKit/Chatbot', '2.7.0'
  pod 'AUIAICall/Chatbot',  :path => "/Users/andy/zwork/three/AUIAICall"
  pod 'AUIFoundation', :path => "/Users/andy/zwork/three/AUIAICall/AUIBaseKits/AUIFoundation/", :modular_headers => true
  # pod 'Firebase/Crashlytics'
  # pod 'Firebase/Analytics'  # 可选，用于增强崩溃上下文


  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config| 
      
      config.build_settings['SWIFT_VERSION'] = '5.0' 
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',
        ## 麦克风
        'PERMISSION_MICROPHONE=1',
        ## 语音识别
        'PERMISSION_SPEECH_RECOGNIZER=1',
        # 相册权限
        'PERMISSION_PHOTOS=1',
        ## 相册
        'PERMISSION_PHOTO_LIBRARY=1',
        ## 相机
        # 'PERMISSION_CAMERA=1',
      ]
    end
  end
end
